# Generated by Django 5.1.5 on 2025-01-27 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_newsitem_detail_url_alter_newsitem_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsitem",
            name="detail_url",
        ),
    ]
