# Generated by Django 5.1.5 on 2025-01-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_newsitem_detail_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
